# Cloud Build config for Module Hub (landing/dashboard).
# Usage: gcloud builds submit --config=cloudbuild.module-hub.yaml --project=PROJECT_ID .
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'Dockerfile.module-hub', '-t', 'gcr.io/$PROJECT_ID/module-hub:latest', '.']
images:
  - 'gcr.io/$PROJECT_ID/module-hub:latest'
