"""Generate the refactor roadmap tracker from the SAME findings the schema
page and the bug log render. Exits non-zero if any bug is unassigned, so a
new finding cannot silently escape the roadmap."""
import importlib.util, sys, os, re, json

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
from refactor_roadmap import PHASES, RULES, OUT_OF_PROGRAM, PHASE_STATUS, PRINCIPLES

spec = importlib.util.spec_from_file_location("c", os.path.join(HERE, "chat_node_content.py"))
m = importlib.util.module_from_spec(spec); spec.loader.exec_module(m)
CONTENT = {}
for name in dir(m):
    v = getattr(m, name)
    if isinstance(v, dict) and v and all(isinstance(x, dict) for x in v.values()):
        CONTENT.update(v)

OWNER_RE = re.compile(r"^OWNER\(([a-z-]+)\):\s*")

bugs = []
for node, rec in CONTENT.items():
    for kind, txt in rec.get("findings", []):
        if kind != "bad":
            continue
        mo = OWNER_RE.match(txt)
        bugs.append({"node": node, "owner": mo.group(1) if mo else None,
                     "text": OWNER_RE.sub("", txt),
                     "rating": rec.get("rating")})

def assign(b):
    for node, sub in PRINCIPLES:
        if node == b["node"] and sub in b["text"]:
            return "PRINCIPLE", None
    for ph, node, sub in RULES:
        if (node is None or node == b["node"]) and sub in b["text"]:
            return ph, None
    for node, sub, bucket, reason in OUT_OF_PROGRAM:
        if node == b["node"] and sub in b["text"]:
            return "OUT", (bucket, reason)
    return None, None

for b in bugs:
    b["phase"], b["out"] = assign(b)

unassigned = [b for b in bugs if b["phase"] is None]

def head(t, n=110):
    return re.sub(r"\s+", " ", t).split(". ")[0][:n]

L = []
w = L.append
w("# Chat refactor — roadmap tracker\n")
w("Generated by `scripts/platform/gen_roadmap.py` from the same findings the schema")
w("page and `chat-schema-findings.md` render. **Do not hand-edit.** The phase")
w("definitions live in `scripts/platform/refactor_roadmap.py`; everything below is")
w("derived.\n")
w("The generator **exits non-zero when a bug is unassigned**, so a new finding is")
w("either sequenced into a phase or given an explicit reason for being outside the")
w("program. That is what makes this a tracker and not a snapshot.\n")
w("Plan and gate definition: `docs/chat-refactor-program.md`. Its sign-off table is")
w("complete as of 2026-09-09 — five of six seats ruled, the sixth (Prompt Studio)")
w("deliberately not yet asked because P4 has not opened. Per-phase status below is")
w("hand-maintained in `refactor_roadmap.py`'s `PHASE_STATUS`, because completion is a")
w("judgement about a gate, not something derivable from the findings file.\n")

inprog = [b for b in bugs if b["phase"] not in (None, "OUT", "PRINCIPLE")]
principles = [b for b in bugs if b["phase"] == "PRINCIPLE"]
out = [b for b in bugs if b["phase"] == "OUT"]
noowner = sum(1 for b in inprog if not b["owner"])
w(f"**{len(bugs)} bugs · {len(inprog)} sequenced into {len(PHASES)} phases · {len(out)} explicitly outside · "
  f"{len(unassigned)} UNSEQUENCED · {noowner} of the {len(inprog)} sequenced have NO OWNER**\n")
w("> The two counts are different questions and the second one used to be invisible.")
w("> `UNSEQUENCED` was previously printed as \"unassigned\", which reads as *nobody owns")
w("> this* but only ever meant *no phase*. Chat Master, reading the generated file rather")
w("> than taking my count, found that a large share of sequenced bugs sit on chat's own")
w("> modules with an empty owner column — so a headline that said `0 unassigned` was green")
w("> at a glance while ownership was largely blank. Both numbers are now printed.\n")

w("## Progress\n")
w("| Phase | Name | Bugs | Owner | Gate metric | Blocks | Status |")
w("|---|---|---:|---|---|---|---|")
for p in PHASES:
    n = sum(1 for b in inprog if b["phase"] == p["id"])
    w(f"| **{p['id']}** | {p['name']} | {n} | {p['owner']} | {p['gate']} | "
      f"{p.get('blocks') or '—'} | {PHASE_STATUS.get(p['id'], '☐ not started')} |")
w("")
w("Phase order is a blocking order: a phase does not open until the phases naming it")
w("in `Blocks` have passed their gate.\n")

w("## By owner\n")
own = {}
for b in inprog:
    own[b["owner"] or "unassigned-owner"] = own.get(b["owner"] or "unassigned-owner", 0) + 1
w("| Owner | Sequenced bugs |")
w("|---|---:|")
for k, v in sorted(own.items(), key=lambda x: -x[1]):
    w(f"| {k} | {v} |")
w("")

for p in PHASES:
    mine = [b for b in inprog if b["phase"] == p["id"]]
    w(f"## {p['id']} — {p['name']}  ·  {len(mine)} items\n")
    w(f"**Owner** {p['owner']}" + (f" · **ratifier** {p['ratifier']}" if p.get("ratifier") else ""))
    w(f"**Gate** {p['gate']}  ")
    w(f"**Blocks** {p.get('blocks') or '—'}\n")
    w(f"> {p['why']}\n")
    w("| ☐ | Node | Owner | Finding |")
    w("|---|---|---|---|")
    for b in sorted(mine, key=lambda x: x["node"]):
        w(f"| ☐ | `{b['node']}` | {b['owner'] or '—'} | {head(b['text'])} |")
    w("")

w("## Outside the program\n")
w("Each carries a reason. Excluding by silence is the failure mode this guards against.\n")
w("| Node | Bucket | Why it is outside | Finding |")
w("|---|---|---|---|")
for b in sorted(out, key=lambda x: (x["out"][0], x["node"])):
    w(f"| `{b['node']}` | {b['out'][0]} | {b['out'][1]} | {head(b['text'], 70)} |")
w("")

w("## Principles — lessons, not defects\n")
w(f"{len(principles)} entries. These are generalisations the program produced, kept")
w("because they are how we now read evidence — and deliberately NOT given checkboxes.")
w("A lesson filed as a bug can never be closed: it sits ☐ forever, inflates its node's")
w("count, and makes the completion metric unreachable by construction. Chat Master's")
w("finding, 2026-09-09.\n")
for b in principles:
    w(f"- **{head(b['text'], 150)}**  \n  _from `{b['node']}`_")
w("")

if unassigned:
    w("## UNASSIGNED — the roadmap is incomplete\n")
    for b in unassigned:
        w(f"- `{b['node']}` — {head(b['text'])}")
    w("")

OUT_PATH = os.path.join(os.path.dirname(HERE), "..", "docs", "chat-refactor-roadmap.md")
OUT_PATH = os.path.normpath(OUT_PATH)
open(OUT_PATH, "w").write("\n".join(L))
print(f"{len(bugs)} bugs · {len(inprog)} sequenced · {len(out)} outside · "
      f"{len(unassigned)} UNASSIGNED -> {OUT_PATH}")
for p in PHASES:
    print(f"  {p['id']} {p['name']:24s} {sum(1 for b in inprog if b['phase']==p['id']):3d}")
if unassigned:
    print("\nUNASSIGNED (roadmap incomplete):", file=sys.stderr)
    for b in unassigned:
        print(f"  {b['node']:24s} {head(b['text'],80)}", file=sys.stderr)
    sys.exit(1)
