#!/usr/bin/env python3
"""The bug/check log — every finding from the chat schema, in one place.

Ananth: "mark all findings in the bug/check log ... lets not get into testing,
lets keep documenting and move forward."

So this is a LOG, not a test plan. Each row is a finding with its node, who
found it, and whether anything is owed. It is generated from the same content
the schema page renders, so the log and the page cannot disagree — which is the
whole reason not to keep a second hand-written list.

Severity comes from the finding's own marker:
  bug     something is wrong and someone should decide what to do
  check   worth knowing, worth watching, not obviously broken
  ok      a positive finding, kept because a verified negative is a result
"""
import importlib.util, json, os, re, sys

ROOT = "/Users/ananth/Mobius"
SEV = {"bad": "BUG", "watch": "CHECK", "good": "OK"}

def load(path, name):
    sp = importlib.util.spec_from_file_location(name, path)
    m = importlib.util.module_from_spec(sp); sp.loader.exec_module(m)
    return m

def lens_of(text):
    t = text.upper()
    for key, lens in (("RUNTIME LENS", "runtime"), ("SCOPE LENS", "scope"),
                      ("STRUCTURE LENS", "structure"), ("STRUCTURE RULING", "structure"),
                      ("DB SEAT", "scope"), ("CHAT SEAT", "owner"),
                      ("TECHNICAL REVIEW", "structure")):
        if key in t:
            return lens
    return "author"

def main():
    C = load(os.path.join(ROOT, "scripts/platform/chat_node_content.py"), "content")
    nodes = {**C.CHAIN, **C.CROSS, **C.SUB}
    sig_path = ("/private/tmp/claude-502/-Users-ananth-Mobius/"
                "7bd378b9-3a8f-4998-a9b3-06f2d630c20f/scratchpad/readiness.json")
    sigs = json.load(open(sig_path)) if os.path.exists(sig_path) else {}
    alias = {"POST /chat": "chat_api", "PHI gate": "phi_gate", "run_pipeline": "orchestrator"}

    rows = []
    for node, d in sorted(nodes.items()):
        for kind, text in d.get("findings", []):
            rows.append({
                "node": node, "rating": d["rating"], "sev": SEV.get(kind, "?"),
                "lens": lens_of(text), "text": " ".join(text.split()),
            })

    bugs   = [r for r in rows if r["sev"] == "BUG"]
    checks = [r for r in rows if r["sev"] == "CHECK"]
    oks    = [r for r in rows if r["sev"] == "OK"]

    out = []
    out.append("# Chat schema — bug / check log\n")
    out.append("Generated by `scripts/platform/gen_findings_log.py` from the same content the\n"
               "schema page renders, so the two cannot drift. Do not hand-edit.\n")
    out.append(f"**{len(bugs)} bugs · {len(checks)} checks · {len(oks)} verified-ok** "
               f"across {len(nodes)} nodes.\n")
    out.append("A verified negative is kept as a result: `OK` rows record things that were\n"
               "checked and found sound, so nobody re-discovers them as findings later.\n")

    by_lens = {}
    for r in rows:
        by_lens.setdefault(r["lens"], {"BUG": 0, "CHECK": 0, "OK": 0})[r["sev"]] += 1
    out.append("\n## Who found what\n")
    out.append("| Lens | Bugs | Checks | OK |")
    out.append("|---|---|---|---|")
    for lens, c in sorted(by_lens.items(), key=lambda kv: -kv[1]["BUG"]):
        out.append(f"| {lens} | {c['BUG']} | {c['CHECK']} | {c['OK']} |")

    out.append("\n## Test coverage per node — catalogue only, no testing done\n")
    out.append("Ananth's instruction was to catalogue whether test files exist, not to run or\n"
               "write any. Eval owns what happens to this column next.\n")
    out.append("| Node | Rating | Test files | Bugs |")
    out.append("|---|---|---|---|")
    for node, d in sorted(nodes.items(), key=lambda kv: (kv[1]["rating"] != "red", kv[0])):
        s = sigs.get(alias.get(node, node), {})
        tests = s.get("tests")
        tcol = ", ".join(t.replace("test_", "").replace(".py", "") for t in tests) if tests else "**none**"
        nbugs = sum(1 for r in bugs if r["node"] == node)
        out.append(f"| `{node}` | {d['rating']} | {tcol} | {nbugs} |")

    for title, group in (("Bugs", bugs), ("Checks", checks), ("Verified OK", oks)):
        out.append(f"\n## {title}\n")
        cur = None
        for r in sorted(group, key=lambda r: (r["rating"] != "red", r["node"])):
            if r["node"] != cur:
                cur = r["node"]
                out.append(f"\n### `{cur}` — {r['rating']}\n")
            out.append(f"- **[{r['lens']}]** {r['text']}")

    path = os.path.join(ROOT, "docs/chat-schema-findings.md")
    open(path, "w").write("\n".join(out) + "\n")
    print(f"{len(bugs)} bugs · {len(checks)} checks · {len(oks)} ok -> {path}")
    untested = [n for n, d in nodes.items()
                if not sigs.get(alias.get(n, n), {}).get("tests")]
    print(f"nodes with NO test file: {len(untested)}/{len(nodes)}")
    red_untested = [n for n in untested if nodes[n]["rating"] == "red"]
    print(f"  of which RED: {red_untested or 'none'}")

if __name__ == "__main__":
    main()
